solon.env: dev

datasource.db:
  type: "com.zaxxer.hikari.HikariDataSource"
  driverClassName: org.h2.Driver
  jdbcUrl: jdbc:h2:mem:jimmer-sql;database_to_upper=true
#  jdbcUrl: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=TRUE;IGNORECASE=TRUE;NON_KEYWORDS=user

jimmer:
  db:
    default-enum-strategy: "ORDINAL"
    trigger-type: "TRANSACTION_ONLY"
    language: java
    defaultBatchSize: 1000
    dialect: org.babyfish.jimmer.sql.dialect.H2Dialect
    offset-optimizing-threshold: 10
    id-only-target-checking-level: ALL
    show-sql: true
    pretty-sql: true

  # You can enable the following configuration line `inline-sql-variables: true`,
  # restart the application and call some REST APIs again to see what happens
  # inline-sql-variables: true

  executor-context-prefixes:
    - org.babyfish.jimmer.sql.example.business
  client:
    ts:
      path: /ts.zip

demo.cache1:
  driverType: "redis" #驱动类型
  keyHeader: "demo" #默认为 ${solon.app.name} ，可不配置
  defSeconds: 30 #默认为 30，可不配置
  server: "localhost:6379"
  db: 0 #默认为 0，可不配置
#  password: ""
  idleConnectionTimeout: 10000
  connectTimeout: 10000

demo.default-tenant: 1

knife4j.enable: true
#knife4j.basic.enable: true
#knife4j.basic.username: admin
#knife4j.basic.password: 123456
knife4j.setting.enableOpenApi: false
knife4j.setting.enableSwaggerModels: false
knife4j.setting.enableFooter: false
